package ru.together.database.entities.auto;

import java.time.LocalDateTime;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ru.together.database.entities.Event;

/**
 * Class _UserPastEvent was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserPastEvent extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<LocalDateTime> CREATE_DATE = Property.create("createDate", LocalDateTime.class);
    public static final Property<LocalDateTime> DELETED_DATE = Property.create("deletedDate", LocalDateTime.class);
    public static final Property<LocalDateTime> MODIFIED_DATE = Property.create("modifiedDate", LocalDateTime.class);
    public static final Property<Event> PAST_TO_EVENT = Property.create("pastToEvent", Event.class);

    public void setCreateDate(LocalDateTime createDate) {
        writeProperty("createDate", createDate);
    }
    public LocalDateTime getCreateDate() {
        return (LocalDateTime)readProperty("createDate");
    }

    public void setDeletedDate(LocalDateTime deletedDate) {
        writeProperty("deletedDate", deletedDate);
    }
    public LocalDateTime getDeletedDate() {
        return (LocalDateTime)readProperty("deletedDate");
    }

    public void setModifiedDate(LocalDateTime modifiedDate) {
        writeProperty("modifiedDate", modifiedDate);
    }
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime)readProperty("modifiedDate");
    }

    public void setPastToEvent(Event pastToEvent) {
        setToOneTarget("pastToEvent", pastToEvent, true);
    }

    public Event getPastToEvent() {
        return (Event)readProperty("pastToEvent");
    }


}
